### ISSUE TITLE
Callback was already called error from async 

### ISSUE THREAD

**Issue by lavayj** [Clever/saml2#115]
const sp = new saml2.ServiceProvider(sso_options.sp_options);
  const params = querystring.parse(event.body);

    // Our field from the request.
    const samlResponse = params['SAMLResponse'];

  log.debug(samlResponse);
  const req ={};
  req.SAMLResponse = samlResponse;
  const options = {request_body:req};
  const idp = new saml2.IdentityProvider(sso_options.idp_options);
  log.debug(options);
   sp.post_assert(idp,options,function(err, assertionResponse){
     if(err){
       log.error(err);
       throw(err);
     } else {

    log.debug(assertionResponse);
    const userId = assertionResponse.user.name_id;
    const firstName = assertionResponse.user.attributes.firstName[0];
    const lastName = assertionResponse.user.attributes.lastName[0];
    const email = assertionResponse.user.attributes.email[0];
    const accessToken = auth.createAccessToken(userId,firstName,lastName,email,'User');

  
  }})})

I get the below error after i receive the assertionResponse and see the log statement. It seems the callback is invoked before completion of the async calls. What could be the issue ?

2017-09-29T16:58:01.202Z	58dea4fa-a537-11e7-ac37-2b1c78b060d2	Error: Callback was already called.
at /var/task/node_modules/saml2-js/node_modules/async/dist/async.js:903:32
at /var/task/node_modules/saml2-js/lib-js/saml2.js:658:16
at nextTask (/var/task/node_modules/saml2-js/node_modules/async/dist/async.js:5297:14)
at next (/var/task/node_modules/saml2-js/node_modules/async/dist/async.js:5304:9)
at /var/task/node_modules/saml2-js/node_modules/async/dist/async.js:906:16
at /var/task/node_modules/saml2-js/lib-js/saml2.js:633:20
at nextTask (/var/task/node_modules/saml2-js/node_modules/async/dist/async.js:5297:14)
at next (/var/task/node_modules/saml2-js/node_modules/async/dist/async.js:5304:9)
at /var/task/node_modules/saml2-js/node_modules/async/dist/async.js:906:16
at /var/task/node_modules/saml2-js/lib-js/saml2.js:607:16

**Comment by rahil471** [comment]
Any solution to thsi issue?

**Comment by rahil471** [comment]
I changed the version to 1.11.1. To fix this. I think the new versions included this bug.

**Comment by JNokikana** [comment]
This is true. Changing the version to 1.11.1 fixed this for me as well.

**Comment by chveragad** [comment]
May i know what was the actual fix on the version 1.11.1 so I can check if this was actually in the later versions? Thanks

**Comment by gabegorelick** [comment]
#112 fixed an instance of this.

**Comment by ComfyDust** [comment]
Ran into this issue recently and found the cause, at least for my instance.

After `post_assert()` returned successfully without error, I mistakenly tried to iterate over response.user with `for (let attribute of response.user)`. Internally the callback function threw `TypeError: response.user is not iterable`.

This error was then [caught in the waterfall](https://github.com/Clever/saml2/blob/cc947c29121b183416a79f263572ba9c86a91291/lib/saml2.coffee#L470) and the code attempted to execute the callback again, this time with the TypeError. This leads to the async package swallowing the original error and throwing its own since the code attempted to execute the callback twice.

I suspect this error might happen if there's any runtime error in the callback. As a workaround until there's a fix it may help to wrap any custom callbacks in a giant try/catch block while debugging.

**Comment by nthgol** [comment]
@ComfyDust thanks for your comment, this led us to a quick fix, indeed you were right. We wrapped our entire callback in a `try catch` and logged the error in the catch to debug

**Comment by pooledge** [comment]
@ComfyDust this comment is terribly underrated
