### ISSUE TITLE
Deflating valid SAMLResponse fails with invalid code lengths set error from zlib

### ISSUE THREAD

**Issue by TheHanna** [Clever/saml2#128]
**OS**: MacOS Sierra 10.12.6
**Node.js version**: 8.9.4
**NPM version**: 5.6.0

I'm encountering the following error when I call `redirect_assert`:

```
invalid code lengths set
Error: invalid code lengths set
    at InflateRaw.zlibOnError (zlib.js:153:15)
```

Full error from the console:

```
{ Error: invalid code lengths set
    at InflateRaw.zlibOnError (zlib.js:153:15) errno: -3, code: 'Z_DATA_ERROR' }
```

The assertion is coming through encrypted from ADFS. The login was a success but for some reason, it can't be deflated by zlib. This is well outside my area of expertise, but I'm getting desperate. Is there anything I can do to get this thing working? I've already tried switching to samlify and that's a non-starter because it can't compile on my local *or* target system.

I can provide a sample for testing over a more private means of communication if needed

**Comment by TheHanna** [comment]
Well I messed this up. I should be using `post_assert` instead. Turns out my issue was that I didn't do anything with the response so my browser would just spin. Banging your head against SAML for 3 days straight really does things to your brain! Closing.
