### ISSUE TITLE
single logout endpoint  saml response failure

### ISSUE THREAD

**Issue by taketomatsunaga** [Clever/saml2#204]
Hi I have been trying to get detail of sample response when IDP sent saml response of single logout service. Is this supported?

```
/**
 * SAML idp logout Endpoint
 */
async function samlAssertLogout(req, res, next) {
    const trx = await sequelizeClient.transaction();
    try {
        let params = req.swagger.params;
        const samlResponse = params.SAMLResponse.value;
        const sigAlg = params.SigAlg.value;
        const signature = params.Signature.value;
        console.log(samlResponse);
        console.log(sigAlg);
        console.log(signature);
        let logoutResponse = await post_assert({
            SAMLResponse: samlResponse,
        });
        console.log(logoutResponse);

        await trx.commit(); // Transaction has been committed

        res.json({});
    } catch (err) {
        await trx.rollback(); // Transaction has been rolled back
        next(err);
    } finally {
    }
}

async function post_assert(samlAssert) {
    var options = {
        request_body: samlAssert,
    };
    return new Promise(function(resolve, reject) {
        sp.post_assert(idp, options, async function(err, saml_response) {
            if (
                err != null ||
                !saml_response.user ||
                saml_response.user.attributes.emailaddress.length == 0
            ) {
                LoggerUtil.logError(err);
                reject(new ApplicationError("E000000007"));
                return;
            }
            resolve(saml_response);
            return;
        });
    });
}
```

```
[2020-06-05T17:20:05.848] [ERROR] [dom-parser.js(179)] [95e816c2-4536-4de7-aba9-5608e30d9cf2] [null] [xmldom error]	element parse error: Error: invalid attribute:�c(G`V�`p�i� 
@#[line:3,col:82]
[xmldom warning]	attribute "�2YEИ3D" missed quot(")!! 
@#[line:3,col:82]
[2020-06-05T17:20:05.849] [ERROR] [dom-parser.js(179)] [95e816c2-4536-4de7-aba9-5608e30d9cf2] [null] [xmldom error]	element parse error: Error: invalid attribute:�c(G`V�`p�i� 
@#[line:3,col:82]
[2020-06-05T17:20:05.849] [INFO] [loggerUtil.js(11)] [95e816c2-4536-4de7-aba9-5608e30d9cf2] [null] Error - Expected 1 Response; found 0
[2020-06-05T17:20:05.849] [INFO] [loggerUtil.js(41)] [95e816c2-4536-4de7-aba9-5608e30d9cf2] [null] Error: Expected 1 Response; found 0
[2020-06-05T17:20:05.850] [INFO] [loggerUtil.js(41)] [95e816c2-4536-4de7-aba9-5608e30d9cf2] [null]     at parse_response_header (/home/taketo/Documents/workspaces/******/app/node_modules/saml2-js/lib-js/saml2.js:419:11)
[2020-06-05T17:20:05.850] [INFO] [loggerUtil.js(41)] [95e816c2-4536-4de7-aba9-5608e30d9cf2] [null]     at /home/taketo/Documents/workspaces/******/app/node_modules/saml2-js/lib-js/saml2.js:830:32
[2020-06-05T17:20:05.850] [INFO] [loggerUtil.js(41)] [95e816c2-4536-4de7-aba9-5608e30d9cf2] [null]     at nextTask (/home/taketo/Documents/workspaces/******/app/node_modules/saml2-js/node_modules/async/dist/async.js:5324:14)
[2020-06-05T17:20:05.850] [INFO] [loggerUtil.js(41)] [95e816c2-4536-4de7-aba9-5608e30d9cf2] [null]     at Immediate.next (/home/taketo/Documents/workspaces/******/app/node_modules/saml2-js/node_modules/async/dist/async.js:5331:9)
[2020-06-05T17:20:05.850] [INFO] [loggerUtil.js(41)] [95e816c2-4536-4de7-aba9-5608e30d9cf2] [null]     at Immediate._onImmediate (/home/taketo/Documents/workspaces/******/app/node_modules/saml2-js/node_modules/async/dist/async.js:969:16)
[2020-06-05T17:20:05.850] [INFO] [loggerUtil.js(41)] [95e816c2-4536-4de7-aba9-5608e30d9cf2] [null]     at processImmediate (internal/timers.js:441:21)
[2020-06-05T17:20:05.850] [INFO] [loggerUtil.js(41)] [95e816c2-4536-4de7-aba9-5608e30d9cf2] [null]     at process.topLevelDomainCallback (domain.js:130:23)
[2020-06-05T17:20:06.026] [INFO] [loggerUtil.js(24)] [95e816c2-4536-4de7-aba9-5608e30d9cf2] [null] E000000007 - Saml authentication failed
[2020-06-05T17:20:06.026] [INFO] [loggerUtil.js(41)] [95e816c2-4536-4de7-aba9-5608e30d9cf2] [null] Error: Saml authentication failed


```

**Comment by taketomatsunaga** [comment]
@jefff

**Comment by taketomatsunaga** [comment]
I found out that this library does not support HTTP Redirect binding.
So I used HTTP Post binding and decode the body as below, then I resolved this issue.
Thank you.

decodeURIComponent(samlResponse)
